"use server";

/**
 * Shot-based Video Generation Server Actions
 *
 * Server actions for managing shots and Veo 3.1 video generation.
 *
 * Shots are created from scene data generated by the generate_scenes_orchestrator
 * n8n workflow. Each shot includes:
 * - Model-specific composition prompts (Seedream 4.5 / Nano Banana Pro)
 * - VEO 3.1 7-component video prompts
 * - Duration, shot type, dialogue segments
 *
 * Workflow:
 * 1. Scenes are parsed with generate_scenes_orchestrator (includes shots)
 * 2. createShotsFromScene extracts shots from scene data
 * 3. Each shot generates video independently (max 8s per shot)
 * 4. Videos are assembled in timeline order for final export
 */

import { db } from '@/lib/drizzle/db.server';
import {
  scene_shots,
  scenes,
  type SceneShot,
  type RawSceneData,
  type Veo3PromptData,
} from '@/lib/drizzle/schema';
import { eq, asc, inArray } from 'drizzle-orm';
// Use process.env directly in server actions (env.server.ts causes bundling issues)
import {
  generateSceneVideo,
  generateImage,
  invokeWorkflow,
  trimVideoClip,
} from '@/lib/n8n/mcp-client';
import type { ApiKeys } from '@/lib/n8n/types';
import { createClient } from '@supabase/supabase-js';

// ============================================================================
// Types
// ============================================================================

export type ShotActionResult =
  | { success: true; shotId?: string; shotIds?: string[]; data?: unknown }
  | { success: false; error: string };

// ============================================================================
// Shot Creation
// ============================================================================

/**
 * Compose video_prompt_veo3 into a single prompt string
 * Veo 3.1 7-component format: subject, action, scene, style, dialogue, sounds, technical
 *
 * NOTE: Content policy compliance is handled by n8n workflow (Claude Haiku rewrite)
 * See workflow "video_generation_simple" for detection and rewriting logic.
 */
function composeVeo3Prompt(vp: {
  subject?: string | null;
  action?: string | null;
  scene?: string | null;
  style?: string | null;
  dialogue?: string | null;
  sounds?: string | null;
  technical?: string | null;
}): string {
  const parts: string[] = [];
  if (vp.subject) parts.push(vp.subject);
  if (vp.action) parts.push(vp.action);
  if (vp.scene) parts.push(vp.scene);
  if (vp.style) parts.push(vp.style);
  if (vp.dialogue) parts.push(vp.dialogue);
  if (vp.sounds) parts.push(vp.sounds);
  if (vp.technical) parts.push(vp.technical);

  return parts.join('. ');
}

/**
 * Create shots from scene data
 *
 * Called after scene parsing when shots array is available.
 * Creates scene_shots records for each shot in the scene.
 *
 * If no shots array exists in scene data, uses AI (scene_to_shots workflow)
 * to intelligently divide the scene into 6-8 second narrative shots.
 *
 * @param sceneId - The scene to create shots for
 * @param apiKeys - Optional API keys for AI shot generation
 * @returns Result with created shot IDs
 */
export async function createShotsFromScene(
  sceneId: string,
  apiKeys?: ApiKeys
): Promise<ShotActionResult> {
  try {
    console.log('🎬 Creating shots for scene:', sceneId);

    // Get the scene
    const [scene] = await db
      .select()
      .from(scenes)
      .where(eq(scenes.id, sceneId))
      .limit(1);

    if (!scene) {
      return { success: false, error: 'Scene not found' };
    }

    // Get shots from full_data OR raw_scene_data (scenes use full_data in MVP)
    const rawData = scene.full_data || scene.raw_scene_data;
    const shotsData = rawData?.shots;

    console.log('📊 Scene data check:', {
      sceneId,
      has_full_data: !!scene.full_data,
      has_raw_scene_data: !!scene.raw_scene_data,
      shots_count: shotsData?.length || 0,
    });

    if (!shotsData || shotsData.length === 0) {
      // No shots in scene data - this means the scene wasn't processed by generate_scenes_orchestrator
      console.log('⚠️ No shots array in scene data');
      return {
        success: false,
        error: 'No shots found in scene data. Please regenerate scenes using the Scene Orchestrator workflow.',
      };
    }

    // Create shots from array
    console.log(`📹 Creating ${shotsData.length} shots from scene data`);

    const createdShots: SceneShot[] = [];
    let previousShotId: string | null = null;

    for (const shotData of shotsData) {
      const isFirstShot = shotData.is_first_shot;
      const usesExtend = !isFirstShot && shotsData.length > 1;

      // Get video_prompt_veo3 structured data from shot (from n8n Scenes workflow)
      const shotVeo3Data = shotData.video_prompt_veo3 || null;
      // Compose action_prompt as fallback
      const composedPrompt = shotVeo3Data
        ? composeVeo3Prompt(shotVeo3Data)
        : shotData.action_prompt;

      // Use model-specific composition as generic fallback
      // The n8n workflow generates composition_instruction_seedream and composition_instruction_nano_banana
      // but not a generic composition_instruction. We use seedream as the default fallback.
      const compositionInstruction =
        shotData.composition_instruction ||
        shotData.composition_instruction_seedream ||
        shotData.composition_instruction_nano_banana ||
        null;

      console.log(`📹 Shot ${shotData.shot_number}:`, {
        has_veo3_data: !!shotVeo3Data,
        veo3_keys: shotVeo3Data ? Object.keys(shotVeo3Data) : [],
        action_prompt_length: composedPrompt?.length || 0,
        has_composition: !!compositionInstruction,
        has_seedream_composition: !!shotData.composition_instruction_seedream,
        has_nano_composition: !!shotData.composition_instruction_nano_banana,
      });

      const insertedShots: SceneShot[] = await db
        .insert(scene_shots)
        .values({
          scene_id: sceneId,
          shot_number: shotData.shot_number,
          shot_duration_seconds: shotData.shot_duration_seconds,
          is_first_shot: isFirstShot,
          shot_type: shotData.shot_type,
          // Use fallback for generic composition_instruction
          composition_instruction: compositionInstruction,
          composition_instruction_seedream: shotData.composition_instruction_seedream,
          composition_instruction_nano_banana: shotData.composition_instruction_nano_banana,
          // Store both structured data AND composed fallback
          video_prompt_veo3: shotVeo3Data,
          action_prompt: composedPrompt,
          end_frame_instruction: shotData.end_frame_instruction,
          dialogue_segment: shotData.dialogue_segment,
          uses_extend: usesExtend,
          previous_shot_id: usesExtend ? previousShotId : null,
          // Set initial status for first shot's start frame (don't auto-trigger)
          start_frame_status: null,
        })
        .returning();

      const insertedShot = insertedShots[0];
      createdShots.push(insertedShot);
      previousShotId = insertedShot.id;
    }

    console.log(`✅ Created ${createdShots.length} shots for scene ${scene.scene_number}`);

    return { success: true, shotIds: createdShots.map((s) => s.id) };
  } catch (error) {
    console.error('❌ Error creating shots:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to create shots',
    };
  }
}

/**
 * Create shots for all scenes in a project
 *
 * Called after all scenes are validated and ready for video generation.
 */
export async function createShotsForProject(
  projectId: string
): Promise<ShotActionResult> {
  try {
    console.log('🎬 Creating shots for project:', projectId);

    const projectScenes = await db
      .select()
      .from(scenes)
      .where(eq(scenes.project_id, projectId))
      .orderBy(asc(scenes.scene_number));

    const allShotIds: string[] = [];

    for (const scene of projectScenes) {
      // Check if shots already exist for this scene
      const existingShots = await db
        .select()
        .from(scene_shots)
        .where(eq(scene_shots.scene_id, scene.id))
        .limit(1);

      if (existingShots.length > 0) {
        console.log(`⏭️ Shots already exist for scene ${scene.scene_number}`);
        continue;
      }

      const result = await createShotsFromScene(scene.id);
      if (result.success && result.shotIds) {
        allShotIds.push(...result.shotIds);
      }
    }

    console.log(`✅ Created ${allShotIds.length} total shots for project`);

    return { success: true, shotIds: allShotIds };
  } catch (error) {
    console.error('❌ Error creating shots for project:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to create shots for project',
    };
  }
}

// ============================================================================
// Shot Frame Generation
// ============================================================================

/**
 * Trigger start frame image generation for a shot
 *
 * Only for first shots that have a composition_instruction.
 * This generates the image that will be used as the first frame in Veo 3.1.
 */
export async function triggerStartFrameGeneration(
  shotId: string
): Promise<ShotActionResult> {
  try {
    console.log('🖼️ Triggering start frame generation for shot:', shotId);

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    if (!shot.composition_instruction) {
      return { success: false, error: 'Shot has no composition_instruction for start frame' };
    }

    // Update status to generating
    await db
      .update(scene_shots)
      .set({ start_frame_status: 'generating' })
      .where(eq(scene_shots.id, shotId));

    // Invoke n8n image generation workflow
    const result = await generateImage({
      prompt: shot.composition_instruction,
      model: 'seedream4.5',
      aspect_ratio: '16:9',
      next_js_callback_url: `${process.env.APP_URL || 'http://localhost:5173'}/api/webhooks/n8n/shot-frame-generated?shot_id=${shotId}&frame_type=start`,
    });

    if (!result.success) {
      await db
        .update(scene_shots)
        .set({
          start_frame_status: 'failed',
          error_message: result.error || 'Failed to start frame generation',
        })
        .where(eq(scene_shots.id, shotId));

      return { success: false, error: result.error || 'Failed to start frame generation' };
    }

    // Store job ID for tracking
    await db
      .update(scene_shots)
      .set({ start_frame_job_id: result.data?.taskId })
      .where(eq(scene_shots.id, shotId));

    console.log('✅ Start frame generation triggered for shot:', shotId);

    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error triggering start frame generation:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to trigger start frame generation',
    };
  }
}

/**
 * Trigger end frame image generation for a shot
 *
 * Only for shots that have an end_frame_instruction.
 * This generates the image that will be used as the last frame in Veo 3.1.
 */
export async function triggerEndFrameGeneration(
  shotId: string
): Promise<ShotActionResult> {
  try {
    console.log('🖼️ Triggering end frame generation for shot:', shotId);

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    if (!shot.end_frame_instruction) {
      return { success: false, error: 'Shot has no end_frame_instruction' };
    }

    // Update status to generating
    await db
      .update(scene_shots)
      .set({ end_frame_status: 'generating' })
      .where(eq(scene_shots.id, shotId));

    // Invoke n8n image generation workflow
    const result = await generateImage({
      prompt: shot.end_frame_instruction,
      model: 'seedream4.5',
      aspect_ratio: '16:9',
      next_js_callback_url: `${process.env.APP_URL || 'http://localhost:5173'}/api/webhooks/n8n/shot-frame-generated?shot_id=${shotId}&frame_type=end`,
    });

    if (!result.success) {
      await db
        .update(scene_shots)
        .set({
          end_frame_status: 'failed',
          error_message: result.error || 'Failed to start end frame generation',
        })
        .where(eq(scene_shots.id, shotId));

      return { success: false, error: result.error || 'Failed to start end frame generation' };
    }

    // Store job ID for tracking
    await db
      .update(scene_shots)
      .set({ end_frame_job_id: result.data?.taskId })
      .where(eq(scene_shots.id, shotId));

    console.log('✅ End frame generation triggered for shot:', shotId);

    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error triggering end frame generation:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to trigger end frame generation',
    };
  }
}

// ============================================================================
// Video Prompt Composition
// ============================================================================

/**
 * Compose a complete video prompt for Veo 3.1
 *
 * Veo 3.1 generates video WITH audio from a single prompt.
 * All audio (dialogue, SFX, ambient, music) must be described in the prompt.
 *
 * Prompt structure:
 * 1. Camera type and movement
 * 2. Main action description
 * 3. Visual atmosphere (lighting, colors)
 * 4. Dialogue with voice description
 * 5. Sound effects and ambient audio
 * 6. Music mood
 *
 * @param shot - The shot data
 * @param scene - The parent scene with full data
 * @returns A complete video generation prompt for Veo 3.1
 */
function composeShotVideoPrompt(
  shot: SceneShot,
  scene: {
    raw_scene_data: RawSceneData | null;
    slugline: string;
  }
): string {
  // PREFER structured VEO 3.1 prompt if available
  // This gives full control over the 7 prompt components
  if (shot.video_prompt_veo3 && Object.values(shot.video_prompt_veo3).some(v => v)) {
    console.log('📹 Using structured VEO3 prompt for shot:', shot.id);
    return composeVeo3Prompt(shot.video_prompt_veo3);
  }

  // Fallback to action_prompt if it exists (composed from video_prompt_veo3 or legacy)
  // NOTE: Content policy compliance is handled by n8n workflow
  if (shot.action_prompt) {
    console.log('📹 Using action_prompt fallback for shot:', shot.id);
    return shot.action_prompt;
  }

  // Legacy: Build prompt from scene data (for shots created before structured prompts)
  console.log('📹 Using legacy scene data for shot:', shot.id);
  const parts: string[] = [];
  const rawData = scene.raw_scene_data;
  const audioReqs = rawData?.audio_requirements;

  // 1. Camera type (shot framing)
  if (shot.shot_type) {
    parts.push(`${shot.shot_type}.`);
  }

  // 2. Camera movement / composition instruction
  if (shot.composition_instruction) {
    parts.push(`Camera: ${shot.composition_instruction}.`);
  } else if (rawData?.composition_instruction) {
    parts.push(`Camera: ${rawData.composition_instruction}.`);
  }

  // 3. Visual atmosphere
  if (rawData?.visual_atmosphere) {
    parts.push(rawData.visual_atmosphere);
  } else if (rawData?.visual_mood?.atmosphere) {
    parts.push(rawData.visual_mood.atmosphere);
  }

  // 4. Lighting
  if (rawData?.visual_mood?.lighting) {
    parts.push(`${rawData.visual_mood.lighting} lighting.`);
  }

  // 5. Color palette
  if (rawData?.visual_mood?.color_palette) {
    parts.push(`${rawData.visual_mood.color_palette} color palette.`);
  }

  // 6. Dialogue with voice type (Veo 3.1 generates spoken audio)
  const dialogue = shot.dialogue_segment ||
    rawData?.dialogue_snippet ||
    audioReqs?.dialogue_transcript;

  if (dialogue) {
    const voiceDesc = audioReqs?.voice_type
      ? ` in a ${audioReqs.voice_type} voice`
      : '';
    const toneDesc = audioReqs?.dialogue_tone
      ? `, ${audioReqs.dialogue_tone}`
      : '';
    parts.push(`Character speaks${voiceDesc}${toneDesc}: "${dialogue}"`);
  }

  // 7. Sound effects
  if (audioReqs?.sfx) {
    const sfxArray = Array.isArray(audioReqs.sfx) ? audioReqs.sfx : [audioReqs.sfx];
    if (sfxArray.length > 0) {
      parts.push(`Sound effects: ${sfxArray.join(', ')}.`);
    }
  }

  // 8. Ambient sounds
  if (audioReqs?.ambient) {
    const ambientArray = Array.isArray(audioReqs.ambient) ? audioReqs.ambient : [audioReqs.ambient];
    if (ambientArray.length > 0) {
      parts.push(`Ambient audio: ${ambientArray.join(', ')}.`);
    }
  }

  // 9. Music mood
  if (audioReqs?.music_mood) {
    parts.push(`Music: ${audioReqs.music_mood}.`);
  } else if (audioReqs?.music) {
    parts.push(`Music: ${audioReqs.music}.`);
  }

  // NOTE: Content policy compliance is handled by n8n workflow
  return parts.join(' ');
}

// ============================================================================
// Scene Video Generation (all shots at once)
// ============================================================================

/**
 * Shot data prepared for n8n workflow
 *
 * Veo 3.1 generates video + audio from a single prompt.
 * The `video_prompt` includes everything: action, camera, dialogue, SFX, music.
 */
interface ShotPayload {
  shot_id: string;
  shot_number: number;
  shot_duration_seconds: number;
  is_first_shot: boolean;
  uses_extend: boolean;

  // Complete Veo 3.1 prompt (includes action, camera, dialogue, SFX, music)
  prompt: string;

  // Images for Veo 3.1 first/last frame generation
  start_frame_image_url: string | null;
  end_frame_image_url: string | null;
}

/**
 * Trigger video generation for ALL shots in a scene
 *
 * Sends all shots to n8n in a single payload.
 * n8n handles the sequential processing:
 * - Shot 1: Generate API with image(s) → taskId_1
 * - Shot 2: Extend API with taskId_1 → taskId_2
 * - Shot 3: Extend API with taskId_2 → taskId_3
 * - etc.
 *
 * n8n polls Kie.ai internally and returns all video URLs when complete.
 */
export async function triggerSceneVideoGeneration(
  sceneId: string
): Promise<ShotActionResult> {
  try {
    console.log('🎬 Triggering video generation for scene:', sceneId);

    // Get the scene
    const [scene] = await db
      .select()
      .from(scenes)
      .where(eq(scenes.id, sceneId))
      .limit(1);

    if (!scene) {
      return { success: false, error: 'Scene not found' };
    }

    // Get all shots for this scene
    const shots = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.scene_id, sceneId))
      .orderBy(asc(scene_shots.shot_number));

    if (shots.length === 0) {
      return { success: false, error: 'No shots found for this scene' };
    }

    // Check that first shot has start frame ready
    const firstShot = shots[0];
    if (!firstShot.start_frame_image_url) {
      return { success: false, error: 'First shot start frame image not ready' };
    }

    // Prepare shots payload for n8n with pre-composed prompts
    // Veo 3.1 generates video + audio from a single prompt
    const shotsPayload: ShotPayload[] = shots.map((shot) => ({
      shot_id: shot.id,
      shot_number: shot.shot_number,
      shot_duration_seconds: shot.shot_duration_seconds,
      is_first_shot: shot.is_first_shot,
      uses_extend: shot.uses_extend,
      prompt: composeShotVideoPrompt(shot, scene),
      start_frame_image_url: shot.start_frame_image_url,
      end_frame_image_url: shot.end_frame_image_url,
    }));

    console.log('📝 Shot payloads prepared:', shotsPayload.map((s) => ({
      shot_number: s.shot_number,
      prompt_preview: s.prompt.substring(0, 150) + (s.prompt.length > 150 ? '...' : ''),
      has_start_frame: !!s.start_frame_image_url,
      has_end_frame: !!s.end_frame_image_url,
    })));

    // Update all shots status to generating
    for (const shot of shots) {
      await db
        .update(scene_shots)
        .set({ video_status: 'generating' })
        .where(eq(scene_shots.id, shot.id));
    }

    // Invoke n8n workflow with ALL shots
    // model (veo3_fast) and aspectRatio (16:9) are set by default in n8n
    const result = await generateSceneVideo({
      scene_id: sceneId,
      scene_number: scene.scene_number,
      slugline: scene.slugline,
      shots: shotsPayload,
    });

    if (!result.success) {
      // Mark all shots as failed
      for (const shot of shots) {
        await db
          .update(scene_shots)
          .set({
            video_status: 'failed',
            error_message: result.error || 'Failed to start video generation',
          })
          .where(eq(scene_shots.id, shot.id));
      }

      return { success: false, error: result.error || 'Failed to start video generation' };
    }

    console.log('✅ Scene video generation triggered:', sceneId, {
      shotCount: shots.length,
      hasExtend: shots.some((s) => s.uses_extend),
    });

    return { success: true, shotIds: shots.map((s) => s.id) };
  } catch (error) {
    console.error('❌ Error triggering scene video generation:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to trigger video generation',
    };
  }
}

/**
 * Trigger video generation for all scenes in a project
 */
export async function triggerProjectVideoGeneration(
  projectId: string
): Promise<ShotActionResult> {
  try {
    console.log('🎬 Triggering video generation for project:', projectId);

    const projectScenes = await db
      .select()
      .from(scenes)
      .where(eq(scenes.project_id, projectId))
      .orderBy(asc(scenes.scene_number));

    const allShotIds: string[] = [];
    const errors: string[] = [];

    for (const scene of projectScenes) {
      const result = await triggerSceneVideoGeneration(scene.id);
      if (result.success && result.shotIds) {
        allShotIds.push(...result.shotIds);
      } else if (!result.success) {
        errors.push(`Scene ${scene.scene_number}: ${result.error}`);
      }
    }

    if (errors.length > 0 && allShotIds.length === 0) {
      return { success: false, error: errors.join('; ') };
    }

    console.log(`✅ Project video generation triggered: ${allShotIds.length} shots`);

    return { success: true, shotIds: allShotIds };
  } catch (error) {
    console.error('❌ Error triggering project video generation:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to trigger project video generation',
    };
  }
}

// ============================================================================
// Query Functions
// ============================================================================

/**
 * Get all shots for a scene
 */
export async function getShotsForScene(sceneId: string) {
  return db
    .select()
    .from(scene_shots)
    .where(eq(scene_shots.scene_id, sceneId))
    .orderBy(asc(scene_shots.shot_number));
}

/**
 * Get shot generation status for a project
 */
export async function getProjectShotStatus(projectId: string): Promise<{
  totalShots: number;
  framesReady: number;
  videosGenerating: number;
  videosReady: number;
  videosFailed: number;
}> {
  const projectScenes = await db
    .select()
    .from(scenes)
    .where(eq(scenes.project_id, projectId));

  let totalShots = 0;
  let framesReady = 0;
  let videosGenerating = 0;
  let videosReady = 0;
  let videosFailed = 0;

  for (const scene of projectScenes) {
    const shots = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.scene_id, scene.id));

    totalShots += shots.length;

    for (const shot of shots) {
      // Check if frames are ready
      const startFrameReady = !shot.composition_instruction || shot.start_frame_status === 'ready';
      const endFrameReady = !shot.end_frame_instruction || shot.end_frame_status === 'ready';

      if (startFrameReady && endFrameReady) {
        framesReady++;
      }

      // Check video status
      if (shot.video_status === 'generating') {
        videosGenerating++;
      } else if (shot.video_status === 'ready' || shot.video_status === 'approved') {
        videosReady++;
      } else if (shot.video_status === 'failed') {
        videosFailed++;
      }
    }
  }

  return {
    totalShots,
    framesReady,
    videosGenerating,
    videosReady,
    videosFailed,
  };
}

// ============================================================================
// MVP Simplified Video Generation
// ============================================================================

/**
 * Generate video for a single shot (MVP: No extend mode)
 *
 * MVP SIMPLIFICATION:
 * - Uses scene's approved image as start frame (no separate frame generation)
 * - Independent 8s video per shot
 * - No chaining with previous shots
 *
 * @param shotId - ID of the shot to generate video for
 * @param apiKeys - Optional user-provided API keys from localStorage
 */
export async function generateShotVideoMVP(
  shotId: string,
  apiKeys?: ApiKeys
): Promise<ShotActionResult> {
  try {
    console.log('🎬 MVP: Generating video for shot:', shotId);

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    // Get scene with approved image
    const [scene] = await db
      .select()
      .from(scenes)
      .where(eq(scenes.id, shot.scene_id))
      .limit(1);

    if (!scene) {
      return { success: false, error: 'Scene not found' };
    }

    // Use shot's own image if available, fallback to scene's approved image
    const imageUrl = shot.start_frame_image_url || scene.approved_image_url;
    if (!imageUrl) {
      return { success: false, error: 'No image for shot. Generate a shot image or approve a scene image first.' };
    }

    // Update status to generating
    await db
      .update(scene_shots)
      .set({
        video_status: 'generating',
        start_frame_image_url: imageUrl, // Store reference to scene image
        updated_at: new Date(),
      })
      .where(eq(scene_shots.id, shotId));

    // Compose video prompt
    const videoPrompt = composeShotVideoPrompt(shot, scene);

    // Call VEO3 via n8n - simplified (no extend)
    // Uses workflow "video_generation_simple" with N8N_VIDEO_GENERATION_SIMPLE_WEBHOOK
    // IMPORTANT: timeout: 0 means no timeout - video generation takes several minutes
    const result = await invokeWorkflow<{ videoUrl?: string; taskId?: string }>(
      'video_generation_simple',
      {
        shotId: shot.id,
        imageUrl,
        prompt: videoPrompt,
        duration: shot.shot_duration_seconds,
        aspectRatio: '16:9',
      },
      { timeout: 0, apiKeys } // No timeout - video generation can take 2-5 minutes
    );

    if (!result.success) {
      await db
        .update(scene_shots)
        .set({
          video_status: 'failed',
          error_message: result.error || 'Video generation failed',
          updated_at: new Date(),
        })
        .where(eq(scene_shots.id, shotId));

      return { success: false, error: result.error || 'Video generation failed' };
    }

    // Store job ID for tracking (async workflow)
    if (result.data?.taskId) {
      await db
        .update(scene_shots)
        .set({
          video_job_id: result.data.taskId,
          veo_task_id: result.data.taskId,
          updated_at: new Date(),
        })
        .where(eq(scene_shots.id, shotId));
    }

    // If synchronous result with video URL
    if (result.data?.videoUrl) {
      await db
        .update(scene_shots)
        .set({
          video_url: result.data.videoUrl,
          video_status: 'ready',
          updated_at: new Date(),
        })
        .where(eq(scene_shots.id, shotId));
    }

    console.log('✅ MVP: Video generation triggered for shot:', shotId);

    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error generating shot video (MVP):', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate video',
    };
  }
}

/**
 * Generate videos for all shots in a project (MVP: Batched, no extend)
 *
 * MVP: Process shots in batches of 3 to avoid overloading n8n
 *
 * @param projectId - Project to generate videos for
 * @param apiKeys - Optional user-provided API keys from localStorage
 */
export async function generateAllShotVideosMVP(
  projectId: string,
  apiKeys?: ApiKeys
): Promise<ShotActionResult> {
  try {
    console.log('🎬 MVP: Generating all shot videos for project:', projectId);

    const MAX_CONCURRENT = 3;

    // Get all shots for the project
    const projectScenes = await db
      .select()
      .from(scenes)
      .where(eq(scenes.project_id, projectId))
      .orderBy(asc(scenes.scene_number));

    // Build a map of scene_id -> approved_image_url for fallback
    const sceneImageMap = new Map<string, string | null>();
    for (const scene of projectScenes) {
      sceneImageMap.set(scene.id, scene.approved_image_url);
    }

    // Get all shots for the project
    const allShots = await db
      .select()
      .from(scene_shots)
      .where(
        inArray(
          scene_shots.scene_id,
          projectScenes.map((s) => s.id)
        )
      )
      .orderBy(asc(scene_shots.shot_number));

    // Filter to shots that:
    // 1. Haven't been processed yet (null or generating)
    // 2. Have an image available (shot's start_frame OR scene's approved image)
    const pendingShots = allShots.filter((shot) => {
      const hasValidStatus = shot.video_status === null || shot.video_status === 'generating';
      const shotImage = shot.start_frame_image_url;
      const sceneImage = sceneImageMap.get(shot.scene_id);
      const hasImage = !!shotImage || !!sceneImage;

      if (!hasValidStatus) {
        return false;
      }

      if (!hasImage) {
        console.log(`⏭️ Skipping shot ${shot.id} - no image available`);
        return false;
      }

      return true;
    });

    console.log(`📊 Found ${pendingShots.length} pending shots to process`);

    // Process in batches of MAX_CONCURRENT
    const allShotIds: string[] = [];

    for (let i = 0; i < pendingShots.length; i += MAX_CONCURRENT) {
      const batch = pendingShots.slice(i, i + MAX_CONCURRENT);
      console.log(`🔄 Processing batch ${Math.floor(i / MAX_CONCURRENT) + 1}: ${batch.length} shots`);

      const results = await Promise.all(
        batch.map((shot) => generateShotVideoMVP(shot.id, apiKeys))
      );

      for (const result of results) {
        if (result.success && result.shotId) {
          allShotIds.push(result.shotId);
        }
      }
    }

    console.log(`✅ MVP: Video generation triggered for ${allShotIds.length} shots`);

    return {
      success: true,
      shotIds: allShotIds,
      data: { queued: allShotIds.length, total: pendingShots.length },
    };
  } catch (error) {
    console.error('❌ Error generating all shot videos (MVP):', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate videos',
    };
  }
}

// ============================================================================
// Shot Reset Actions (for fixing existing data)
// ============================================================================

/**
 * Reset shots for a scene - delete existing and recreate from full_data
 *
 * Use this to fix shots that were created with wrong/missing data.
 */
export async function resetShotsForScene(sceneId: string): Promise<ShotActionResult> {
  try {
    console.log('🔄 Resetting shots for scene:', sceneId);

    // Delete existing shots
    const deletedShots = await db
      .delete(scene_shots)
      .where(eq(scene_shots.scene_id, sceneId))
      .returning();

    console.log(`🗑️ Deleted ${deletedShots.length} existing shots`);

    // Recreate from scene data
    const result = await createShotsFromScene(sceneId);

    if (result.success) {
      console.log(`✅ Recreated ${result.shotIds?.length || 0} shots for scene`);
    }

    return result;
  } catch (error) {
    console.error('❌ Error resetting shots for scene:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to reset shots',
    };
  }
}

/**
 * Reset shots for all scenes in a project
 *
 * Use this to fix all shots that were created with wrong/missing data.
 */
export async function resetShotsForProject(projectId: string): Promise<ShotActionResult> {
  try {
    console.log('🔄 Resetting all shots for project:', projectId);

    const projectScenes = await db
      .select()
      .from(scenes)
      .where(eq(scenes.project_id, projectId))
      .orderBy(asc(scenes.scene_number));

    const allShotIds: string[] = [];
    let totalDeleted = 0;

    for (const scene of projectScenes) {
      // Delete existing shots
      const deletedShots = await db
        .delete(scene_shots)
        .where(eq(scene_shots.scene_id, scene.id))
        .returning();

      totalDeleted += deletedShots.length;

      // Recreate from scene data
      const result = await createShotsFromScene(scene.id);
      if (result.success && result.shotIds) {
        allShotIds.push(...result.shotIds);
      }
    }

    console.log(`✅ Reset complete: deleted ${totalDeleted} old shots, created ${allShotIds.length} new shots`);

    return { success: true, shotIds: allShotIds };
  } catch (error) {
    console.error('❌ Error resetting shots for project:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to reset shots',
    };
  }
}

/**
 * Regenerate shots for all scenes from scene data
 *
 * Deletes existing shots and recreates them from raw_scene_data.shots.
 * This is useful after regenerating scenes with the orchestrator workflow.
 *
 * @param projectId - Project to regenerate shots for
 */
export async function regenerateAllShots(
  projectId: string
): Promise<ShotActionResult> {
  // Delegate to resetShotsForProject which handles the delete + recreate logic
  return resetShotsForProject(projectId);
}

// ============================================================================
// Shot Update Actions
// ============================================================================

/**
 * Update a shot's action prompt (video prompt)
 *
 * This allows users to edit the video generation prompt before generating.
 */
export async function updateShotPrompt(
  shotId: string,
  newPrompt: string
): Promise<ShotActionResult> {
  try {
    console.log('📝 Updating shot prompt:', shotId);

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    // Update both composition_instruction (used for image generation)
    // and action_prompt (fallback for video generation)
    await db
      .update(scene_shots)
      .set({
        composition_instruction: newPrompt,
        action_prompt: newPrompt,
        updated_at: new Date(),
      })
      .where(eq(scene_shots.id, shotId));

    // Get scene to revalidate the correct path
    const [scene] = await db
      .select()
      .from(scenes)
      .where(eq(scenes.id, shot.scene_id))
      .limit(1);

    console.log('✅ Shot prompt updated:', shotId);
    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error updating shot prompt:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to update prompt',
    };
  }
}

/**
 * Update a shot's structured VEO 3.1 prompt data
 *
 * Updates both the structured video_prompt_veo3 JSONB field and
 * composes a new action_prompt from the structured data for fallback.
 *
 * @param shotId - Shot ID to update
 * @param promptData - The 7-component VEO 3.1 prompt structure
 */
export async function updateShotVeo3Prompt(
  shotId: string,
  promptData: Veo3PromptData
): Promise<ShotActionResult> {
  try {
    console.log('📝 Updating shot VEO3 prompt:', shotId);
    console.log('📝 Received promptData:', JSON.stringify(promptData, null, 2));

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    // Compose a single-string prompt from structured data (for fallback)
    const composedPrompt = composeVeo3Prompt(promptData);
    console.log('📝 Composed prompt:', composedPrompt.substring(0, 100) + '...');

    await db
      .update(scene_shots)
      .set({
        video_prompt_veo3: promptData,
        action_prompt: composedPrompt,
        updated_at: new Date(),
      })
      .where(eq(scene_shots.id, shotId));

    // Verify the update by reading back the data
    const [updatedShot] = await db
      .select({
        id: scene_shots.id,
        video_prompt_veo3: scene_shots.video_prompt_veo3,
        action_prompt: scene_shots.action_prompt,
      })
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    console.log('✅ Shot VEO3 prompt updated:', shotId);
    console.log('✅ Verified data after save:', JSON.stringify(updatedShot?.video_prompt_veo3, null, 2));

    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error updating shot VEO3 prompt:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to update VEO3 prompt',
    };
  }
}

// ============================================================================
// Shot Cancel Actions
// ============================================================================

/**
 * Cancel video generation for a single shot
 *
 * Resets video_status from 'generating' to null so user can retry.
 */
export async function cancelShotVideoGeneration(
  shotId: string
): Promise<ShotActionResult> {
  try {
    console.log('🛑 Cancelling video generation for shot:', shotId);

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    if (shot.video_status !== 'generating') {
      return { success: false, error: 'Shot is not currently generating' };
    }

    await db
      .update(scene_shots)
      .set({
        video_status: null,
        video_job_id: null,
        error_message: 'Cancelled by user',
        updated_at: new Date(),
      })
      .where(eq(scene_shots.id, shotId));

    // Get scene to revalidate the correct path
    const [scene] = await db
      .select()
      .from(scenes)
      .where(eq(scenes.id, shot.scene_id))
      .limit(1);

    console.log('✅ Shot video generation cancelled:', shotId);
    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error cancelling shot video generation:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to cancel generation',
    };
  }
}

/**
 * Manually update shot video result
 *
 * Used to fix shots that failed to update via webhook but actually succeeded.
 * Sets video URL, status, and task ID directly.
 */
export async function updateShotVideoResult(
  shotId: string,
  videoUrl: string,
  taskId?: string
): Promise<ShotActionResult> {
  try {
    console.log('🔧 Manually updating shot video result:', shotId);

    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    await db
      .update(scene_shots)
      .set({
        video_url: videoUrl,
        video_status: 'ready',
        veo_task_id: taskId || shot.veo_task_id,
        error_message: null,
        updated_at: new Date(),
      })
      .where(eq(scene_shots.id, shotId));

    // Get scene to revalidate the correct path
    const [scene] = await db
      .select()
      .from(scenes)
      .where(eq(scenes.id, shot.scene_id))
      .limit(1);

    console.log('✅ Shot video result updated:', shotId, { videoUrl });
    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error updating shot video result:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to update shot video result',
    };
  }
}

/**
 * Delete a single shot
 *
 * Removes the shot from the database and renumbers remaining shots
 * in the scene to maintain sequential numbering (1, 2, 3...).
 *
 * @param shotId - ID of the shot to delete
 */
export async function deleteShot(shotId: string): Promise<ShotActionResult> {
  try {
    console.log('🗑️ Deleting shot:', shotId);

    // Get the shot to find its scene_id
    const [shot] = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    // Prevent deletion of shots currently generating
    if (shot.video_status === 'generating') {
      return { success: false, error: 'Cannot delete a shot that is currently generating. Cancel generation first.' };
    }

    const sceneId = shot.scene_id;

    // Delete the shot
    await db.delete(scene_shots).where(eq(scene_shots.id, shotId));

    console.log('🗑️ Shot deleted, renumbering remaining shots...');

    // Get remaining shots for this scene, ordered by current shot_number
    const remainingShots = await db
      .select()
      .from(scene_shots)
      .where(eq(scene_shots.scene_id, sceneId))
      .orderBy(asc(scene_shots.shot_number));

    // Renumber shots sequentially (1, 2, 3...)
    for (let i = 0; i < remainingShots.length; i++) {
      const newNumber = i + 1;
      const currentShot = remainingShots[i];

      if (currentShot.shot_number !== newNumber) {
        await db
          .update(scene_shots)
          .set({
            shot_number: newNumber,
            is_first_shot: newNumber === 1,
            updated_at: new Date(),
          })
          .where(eq(scene_shots.id, currentShot.id));
      }
    }

    console.log(`✅ Shot deleted and ${remainingShots.length} remaining shots renumbered`);

    return { success: true, shotId };
  } catch (error) {
    console.error('❌ Error deleting shot:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to delete shot',
    };
  }
}

/**
 * Cancel video generation for all shots in a project
 *
 * Resets all shots with video_status='generating' to null.
 */
export async function cancelAllProjectVideoGeneration(
  projectId: string
): Promise<ShotActionResult> {
  try {
    console.log('🛑 Cancelling all video generation for project:', projectId);

    // Get all scenes for this project
    const projectScenes = await db
      .select({ id: scenes.id })
      .from(scenes)
      .where(eq(scenes.project_id, projectId));

    const sceneIds = projectScenes.map((s) => s.id);

    if (sceneIds.length === 0) {
      return { success: true, shotIds: [] };
    }

    // Update all generating shots for these scenes
    const { inArray } = await import('drizzle-orm');

    const updatedShots = await db
      .update(scene_shots)
      .set({
        video_status: null,
        video_job_id: null,
        error_message: 'Cancelled by user',
        updated_at: new Date(),
      })
      .where(
        eq(scene_shots.video_status, 'generating')
      )
      .returning({ id: scene_shots.id, scene_id: scene_shots.scene_id });

    // Filter to only shots belonging to this project's scenes
    const projectShotIds = updatedShots
      .filter((shot) => sceneIds.includes(shot.scene_id))
      .map((shot) => shot.id);

    console.log(`✅ Cancelled ${projectShotIds.length} generating shots`);
    return { success: true, shotIds: projectShotIds };
  } catch (error) {
    console.error('❌ Error cancelling project video generation:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to cancel generation',
    };
  }
}

// ============================================================================
// Video Trimming
// ============================================================================

/**
 * Upload a trimmed video to Supabase Storage for permanent storage
 * @param tempUrl - Temporary URL from FFmpeg API
 * @param projectId - Project ID for file organization
 * @param shotId - Shot ID for unique filename
 * @returns Permanent Supabase public URL
 */
async function uploadTrimmedVideoToSupabase(
  tempUrl: string,
  projectId: string,
  shotId: string
): Promise<string> {
  const supabaseUrl = process.env.SUPABASE_URL!;
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

  const supabase = createClient(supabaseUrl, supabaseServiceKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });

  console.log('📥 Downloading trimmed video from temporary URL...');

  // Download the video from FFmpeg API
  const response = await fetch(tempUrl);

  if (!response.ok) {
    throw new Error(`Failed to download trimmed video: ${response.status} ${response.statusText}`);
  }

  const videoBuffer = await response.arrayBuffer();
  const videoSize = videoBuffer.byteLength;
  console.log(`📦 Downloaded trimmed video: ${(videoSize / 1024 / 1024).toFixed(2)}MB`);

  // Generate unique filename under project folder
  const timestamp = Date.now();
  const filename = `${projectId}/shots/${shotId}-trimmed-${timestamp}.mp4`;

  console.log('📤 Uploading trimmed video to Supabase Storage...');

  // Upload to Supabase Storage (videos bucket)
  const { error } = await supabase.storage
    .from('videos')
    .upload(filename, videoBuffer, {
      contentType: 'video/mp4',
      upsert: true,
    });

  if (error) {
    throw new Error(`Supabase upload failed: ${error.message}`);
  }

  // Get public URL
  const { data: urlData } = supabase.storage
    .from('videos')
    .getPublicUrl(filename);

  if (!urlData?.publicUrl) {
    throw new Error('Failed to get public URL for trimmed video');
  }

  console.log('✅ Trimmed video uploaded to Supabase:', urlData.publicUrl);

  return urlData.publicUrl;
}

/**
 * Trim a shot's video using FFmpeg API via n8n workflow
 *
 * MVP: This permanently replaces the video URL with the trimmed version.
 * Uses fast copy mode (no re-encoding) for near-instant trimming (~1-2 seconds).
 * The trimmed video is uploaded to Supabase Storage for permanent access.
 *
 * @param shotId - ID of the shot to trim
 * @param startTime - Trim start point in seconds
 * @param endTime - Trim end point in seconds
 * @returns Result with new video URL on success
 */
export async function trimShotVideo(
  shotId: string,
  startTime: number,
  endTime: number,
  mode: 'fast' | 'precise' = 'fast'
): Promise<{ success: boolean; error?: string; videoUrl?: string; duration?: number }> {
  try {
    console.log('✂️ Trimming shot video:', { shotId, startTime, endTime });

    // Validate trim points
    if (startTime < 0) {
      return { success: false, error: 'Start time cannot be negative' };
    }

    if (endTime <= startTime) {
      return { success: false, error: 'End time must be greater than start time' };
    }

    // Get the shot with scene info to get project_id
    const [shot] = await db
      .select({
        id: scene_shots.id,
        scene_id: scene_shots.scene_id,
        video_url: scene_shots.video_url,
        shot_duration_seconds: scene_shots.shot_duration_seconds,
      })
      .from(scene_shots)
      .where(eq(scene_shots.id, shotId))
      .limit(1);

    if (!shot) {
      return { success: false, error: 'Shot not found' };
    }

    if (!shot.video_url) {
      return { success: false, error: 'Shot has no video to trim' };
    }

    // Get the scene to find the project_id
    const [scene] = await db
      .select({ project_id: scenes.project_id })
      .from(scenes)
      .where(eq(scenes.id, shot.scene_id))
      .limit(1);

    if (!scene) {
      return { success: false, error: 'Scene not found for shot' };
    }

    // Validate that trim points are within video duration
    if (shot.shot_duration_seconds && endTime > shot.shot_duration_seconds) {
      return {
        success: false,
        error: `End time (${endTime}s) exceeds video duration (${shot.shot_duration_seconds}s)`,
      };
    }

    // Call n8n workflow to trim the video
    const result = await trimVideoClip({
      shotId,
      videoUrl: shot.video_url,
      start: startTime,
      end: endTime,
      mode,
    });

    if (!result.success || !result.data?.videoUrl) {
      console.error('❌ Trim workflow failed:', result.error);
      return {
        success: false,
        error: result.error || 'Failed to trim video',
      };
    }

    const tempTrimmedUrl = result.data.videoUrl;
    const newDuration = result.data.duration || (endTime - startTime);

    // Upload trimmed video to Supabase for permanent storage
    // This prevents the trimmed URL from expiring (FFmpeg API URLs expire in ~2 hours)
    let permanentVideoUrl: string;
    try {
      permanentVideoUrl = await uploadTrimmedVideoToSupabase(
        tempTrimmedUrl,
        scene.project_id,
        shotId
      );
    } catch (uploadError) {
      console.error('⚠️ Supabase upload failed, using temporary URL:', uploadError);
      // Fallback to temporary URL if upload fails
      // User will need to re-trim if they want to use this in assembly later
      permanentVideoUrl = tempTrimmedUrl;
    }

    // Update the shot with the permanent video URL and duration
    await db
      .update(scene_shots)
      .set({
        video_url: permanentVideoUrl,
        shot_duration_seconds: Math.round(newDuration),
        updated_at: new Date(),
      })
      .where(eq(scene_shots.id, shotId));

    console.log('✅ Shot video trimmed:', {
      shotId,
      originalUrl: shot.video_url.substring(0, 50) + '...',
      permanentUrl: permanentVideoUrl.substring(0, 50) + '...',
      newDuration,
    });

    return {
      success: true,
      videoUrl: permanentVideoUrl,
      duration: newDuration,
    };
  } catch (error) {
    console.error('❌ Error trimming shot video:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to trim video',
    };
  }
}

/**
 * Find and fix shots with expired FFmpeg API URLs
 *
 * Temporary URLs (FFmpeg API + tempfile.aiquickdraw.com)
 * expire after ~2 hours. This function:
 * 1. Finds all shots with these temporary URLs
 * 2. Checks if each URL is still accessible
 * 3. For expired URLs, resets video_status to 'pending' so user can regenerate
 *
 * @param projectId - Project ID to check
 * @returns List of fixed shot IDs
 */
export async function fixExpiredVideoUrls(
  projectId: string
): Promise<{ success: boolean; fixedShots?: string[]; error?: string }> {
  try {
    console.log('🔍 Checking for expired video URLs in project:', projectId);

    // Get all scenes for this project
    const projectScenes = await db
      .select({ id: scenes.id })
      .from(scenes)
      .where(eq(scenes.project_id, projectId));

    if (projectScenes.length === 0) {
      return { success: true, fixedShots: [] };
    }

    const sceneIds = projectScenes.map(s => s.id);

    const tempHosts = ['apps-ffmpeg-api', 'tempfile.aiquickdraw.com'];
    const isTemporaryVideoUrl = (url?: string | null) =>
      typeof url === 'string' && tempHosts.some((host) => url.includes(host));

    const isTemporaryVideoUrlAccessible = async (url: string): Promise<boolean> => {
      try {
        const headResponse = await fetch(url, { method: 'HEAD' });
        if (headResponse.ok) return true;

        if (headResponse.status === 405 || headResponse.status === 400) {
          const rangeResponse = await fetch(url, {
            method: 'GET',
            headers: { Range: 'bytes=0-0' },
          });
          return rangeResponse.ok;
        }

        return false;
      } catch {
        return false;
      }
    };

    // Find all shots for this project with temporary URLs
    const shotsWithTempUrls = await db
      .select({
        id: scene_shots.id,
        video_url: scene_shots.video_url,
        shot_number: scene_shots.shot_number,
      })
      .from(scene_shots)
      .where(inArray(scene_shots.scene_id, sceneIds));

    // Filter to only temporary URLs
    const tempShots = shotsWithTempUrls.filter((shot) => isTemporaryVideoUrl(shot.video_url));

    if (tempShots.length === 0) {
      console.log('✅ No expired temporary URLs found');
      return { success: true, fixedShots: [] };
    }

    console.log(`🔍 Found ${tempShots.length} shots with temporary URLs, checking accessibility...`);

    const fixedShots: string[] = [];

    for (const shot of tempShots) {
      if (!shot.video_url) continue;

      // Check if URL is still accessible
      try {
        const isAccessible = await isTemporaryVideoUrlAccessible(shot.video_url);
        if (!isAccessible) {
          // URL is expired/not found - reset the shot
          console.log(`⚠️ Shot ${shot.id} (shot #${shot.shot_number}) has expired URL, resetting...`);

          await db
            .update(scene_shots)
            .set({
              video_url: null,
              video_status: null, // null means "pending" (not yet triggered)
              updated_at: new Date(),
            })
            .where(eq(scene_shots.id, shot.id));

          fixedShots.push(shot.id);
        } else {
          console.log(`✅ Shot ${shot.id} URL is still accessible`);
        }
      } catch {
        // Network error - assume expired
        console.log(`⚠️ Shot ${shot.id} URL check failed, resetting...`);

        await db
          .update(scene_shots)
          .set({
            video_url: null,
            video_status: null, // null means "pending" (not yet triggered)
            updated_at: new Date(),
          })
          .where(eq(scene_shots.id, shot.id));

        fixedShots.push(shot.id);
      }
    }

    console.log(`✅ Fixed ${fixedShots.length} shots with expired URLs`);

    return {
      success: true,
      fixedShots,
    };
  } catch (error) {
    console.error('❌ Error fixing expired URLs:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to fix expired URLs',
    };
  }
}
