"use client";

/**
 * Create Shots Button Component
 *
 * Button to create shots for a scene directly from the Images page.
 * Uses the shots.createShotsFromScene server action via RPC.
 * Shots are extracted from raw_scene_data.shots (generated by orchestrator workflow).
 *
 * Two-step process:
 * 1. Create Shots: Extracts shot definitions from scene data to scene_shots table
 * 2. Generate Images: User selects model (Seedream/Nano Banana) per shot in ShotImageCard
 */

import { useState } from "react";
import { useRevalidator } from "react-router";
import { Button } from "@/components/ui/button";
import { Wand2, Loader2, AlertCircle } from "lucide-react";
import { getApiKeysFromStorage } from "@/hooks/use-api-keys";

interface CreateShotsButtonProps {
  sceneId: string;
  sceneNumber: number;
}

export function CreateShotsButton({ sceneId, sceneNumber }: CreateShotsButtonProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const revalidator = useRevalidator();

  const handleCreateShots = async () => {
    setIsLoading(true);
    setError(null);
    setSuccess(false);

    console.log(`🎬 [CreateShotsButton] Creating shots for scene ${sceneNumber} (${sceneId})`);

    try {
      // Get API keys from localStorage
      const apiKeys = getApiKeysFromStorage();

      // Call the shots.createShotsFromScene action via RPC
      // This extracts shots from raw_scene_data.shots to scene_shots table
      const response = await fetch("/api/rpc", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          module: "shots",
          method: "createShotsFromScene",
          args: [sceneId, apiKeys],
        }),
      });

      console.log(`🔄 [CreateShotsButton] RPC response status:`, response.status);

      const result = await response.json();
      console.log(`📊 [CreateShotsButton] RPC result:`, result);

      if (!result.success) {
        console.error(`❌ [CreateShotsButton] Failed:`, result.error);
        setError(result.error || "Failed to create shots");
        return;
      }

      console.log(`✅ [CreateShotsButton] Created ${result.shotIds?.length || 0} shots for scene ${sceneNumber}`);
      setSuccess(true);

      // Revalidate to refresh the page and show ShotImageCard components
      revalidator.revalidate();
    } catch (err) {
      console.error("❌ [CreateShotsButton] Network error:", err);
      setError(err instanceof Error ? err.message : "Failed to create shots");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center gap-3">
      <Button
        onClick={handleCreateShots}
        disabled={isLoading || success}
        className="bg-[#f5c518] hover:bg-[#f5c518]/90 text-black font-oswald uppercase tracking-wider"
      >
        {isLoading ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Creating Shots...
          </>
        ) : success ? (
          <>
            <Wand2 className="mr-2 h-4 w-4" />
            Shots Created!
          </>
        ) : (
          <>
            <Wand2 className="mr-2 h-4 w-4" />
            Create Shots
          </>
        )}
      </Button>
      <p className="text-[#666] font-courier text-xs text-center max-w-[280px]">
        Step 1: Extract shots from scene data.
        <br />
        Step 2: Generate images per shot with model selection.
      </p>
      {error && (
        <div className="flex items-start gap-2 p-3 bg-red-500/10 border border-red-500/30 rounded-lg max-w-[320px]">
          <AlertCircle className="h-4 w-4 text-red-400 mt-0.5 flex-shrink-0" />
          <p className="text-red-400 font-courier text-xs">{error}</p>
        </div>
      )}
      {success && (
        <p className="text-green-400 font-courier text-xs">
          Refreshing to show shot cards...
        </p>
      )}
    </div>
  );
}
